# Generated by Django 4.0.6 on 2022-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('money', models.DecimalField(decimal_places=2, max_digits=100)),
                ('time_played', models.DateTimeField()),
            ],
        ),
    ]
