# Generated by Django 4.0.6 on 2022-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
