# Generated by Django 4.0.6 on 2022-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_userinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='amount_object',
            field=models.IntegerField(null=True),
        ),
    ]
