# Generated by Django 4.0.6 on 2022-07-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_userinfo_amount_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='amount_object',
        ),
        migrations.CreateModel(
            name='object_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=40)),
                ('object_number', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_info', to='userData.userinfo')),
            ],
            options={
                'ordering': ['object'],
                'unique_together': {('object', 'object_number')},
            },
        ),
    ]
