# Generated by Django 4.0.6 on 2022-07-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0005_alter_userinfo_options_remove_userinfo_amount_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('object_amount', models.IntegerField()),
                ('object_price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['username']},
        ),
        migrations.DeleteModel(
            name='object_info',
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='userData.userinfo'),
        ),
    ]
